name: Run Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'  # Adjust this to match your project's Go version

      - name: Download dependencies
        run: go mod download

      - name: Run tests
        run: make test
